name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build Flutter Android SDK Docker Image
    uses: ./.github/workflows/flutter-android-sdk.yml
