name: ci

on:
  push:
    branches:
      - "main"

env:
  JDK_VERSION: 17
  ANDROID_VERSION: 33
  FLUTTER_VERSION: 3.24.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}

      - name: Build and push full image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.full
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-full

      - name: Build and push android-arm image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.android-arm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-android-arm

      - name: Build and push android-arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.android-arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-android-arm64

      - name: Build and push android-x64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.android-x64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-android-x64

      - name: Build and push linux-x64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.linux-x64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-linux-x64

      - name: Build and push darwin-x64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.darwin-x64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-darwin-x64

      - name: Build and push windows-x64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.windows-x64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flutter-android-sdk:jdk${{ env.JDK_VERSION }}-android${{ env.ANDROID_VERSION }}-flutter${{ env.FLUTTER_VERSION }}-windows-x64